name: aapli_society
description: Aapli Society multi-tenant resident & security app
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  go_router: ^14.2.0
  dio: ^5.5.0
  file_picker: ^8.1.2
  flutter_secure_storage: ^9.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  socket_io_client: ^2.0.3+1
  firebase_core: ^3.2.0
  firebase_remote_config: ^5.0.3
  firebase_messaging: ^15.0.4
  permission_handler: ^11.3.1
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  url_launcher: ^6.3.0
  share_plus: ^12.0.2
  image_picker: ^1.1.2
  toastification: ^3.2.0
  printing: ^5.14.2
  pdf: ^3.11.1
  image: ^4.2.0
  cupertino_icons: ^1.0.9
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
flutter:
  uses-material-design: true
  assets:
    - assets/icon/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#0C2461"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  remove_alpha_ios: true