export const NOTIFICATION_TYPES = {
  BILL_GENERATED: "BILL_GENERATED",
  PAYMENT_RECEIVED: "PAYMENT_RECEIVED",
  NOTICE_POSTED: "NOTICE_POSTED",
  COMPLAINT_APPROVED: "COMPLAINT_APPROVED",
  COMPLAINT_REJECTED: "COMPLAINT_REJECTED",
  VISITOR_APPROVAL: "VISITOR_APPROVAL",
  VISITOR_DECISION: "VISITOR_DECISION",
  VISITOR_ENTERED: "VISITOR_ENTERED",
  VISITOR_EXITED: "VISITOR_EXITED",
  VISITOR_ESCALATION: "VISITOR_ESCALATION",
  VISITOR_PASS: "VISITOR_PASS",
  VISITOR_SOS: "VISITOR_SOS",
  SECURITY_ALERT: "SECURITY_ALERT",
  TENANT_LEASE_EXPIRED: "TENANT_LEASE_EXPIRED",
} as const
export type NotificationType = (typeof NOTIFICATION_TYPES)[keyof typeof NOTIFICATION_TYPES]

export const RECIPIENT_TYPES = ["all", "member", "wing", "flats", "role", "user"] as const
export type RecipientType = (typeof RECIPIENT_TYPES)[number]

export const DELIVERY_CHANNELS = ["in_app", "push", "sms", "whatsapp", "email", "guard_call", "admin_alert"] as const
export type DeliveryChannel = (typeof DELIVERY_CHANNELS)[number]
